In [104]:
import json
from datetime import datetime, timedelta
import pandas as pd
import glob
import os
from sentence_transformers import SentenceTransformer, util
import torch
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import spacy

/opt/anaconda3/lib/python3.8/site-packages/torch/__init__.py:696: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/tensor/python_tensor.cpp:453.)
  _C._set_default_tensor_type(t)

## Setting Directory

In [8]:
os.chdir("/Users/alexlin/Desktop/R For Substack/news_coverage/")

In [9]:
os.getcwd()

'/Users/alexlin/Desktop/R For Substack/news_coverage'

## Importing Data

In [10]:
# nyt data
nyt_mst_path = f"data/mst/00_nyt_articles.csv"
nyt_articles = pd.read_csv(nyt_mst_path)

# acled filtered data
acled_mst_path = f"data/mst/00b_acled_events_filter.csv"
acled_events_filter = pd.read_csv(acled_mst_path)

## Importing NYT embeddings

In [11]:
nyt_embeddings = np.load(f"data/mst/sentence_embeddings/01_nyt_embeddings.npy")

In [13]:
len(nyt_embeddings)

11818

## Grouping ACLED events

In [14]:
acled_events_filter.head(2)

,Unnamed: 0,event_date,year,disorder_type,event_type,sub_event_type,actor1,actor2,interaction,region,country,fatalities,notes,tags,event_index,cross_join_key
0,58,2024-03-31,2024,Political violence,Battles,Armed clash,Murle Ethnic Militia (South Sudan),Anyuak Ethnic Militia (South Sudan),Identity militia-Identity militia,Eastern Africa,South Sudan,10,"On 31 March 2024, suspected members of Murle a...",NaN,0,1
1,62,2024-03-31,2024,Political violence,Violence against civilians,Attack,Rapid Support Forces,Civilians (Sudan),Rebel group-Civilians,Northern Africa,Sudan,9,"Around 31 March 2024 (as reported), RSF attack...",NaN,1,1

In [90]:
acled_events_grouped = acled_events_filter.groupby(['country', 'actor1', 'actor2']).agg({
    'fatalities': 'sum',
    'notes': lambda x: " ".join(x)
})

acled_events_grouped = pd.DataFrame(acled_events_grouped).reset_index()

# getting rid of dates in the notes col

date_pattern = "On \d{1,2}\s+\w*\s+\d{4}, "
acled_events_grouped['notes'] = acled_events_grouped['notes'].str.replace(date_pattern, '', regex=True)

# setting an index/counter
acled_events_grouped['event_index'] = acled_events_grouped.index

In [91]:
acled_events_grouped.head(10)

,country,actor1,actor2,fatalities,notes,event_index
0,Afghanistan,Islamic State Khorasan Province (ISKP),Military Forces of Afghanistan (2021-),22,21-43 Taliban members and civilians were kille...,0
1,Afghanistan,Military Forces of Pakistan (2022-),Civilians (Afghanistan),6,"six civilians, three women and three children,...",1
2,Afghanistan,National Resistance Front,Military Forces of Afghanistan (2021-),9,five Taliban members were killed and two were ...,2
3,Afghanistan,Unidentified Armed Group (Afghanistan),Civilians (Afghanistan),9,Explosive remnants of war: at least nine child...,3
4,Angola,FLEC-FAC: Front for the Liberation of the Encl...,Military Forces of Angola (1975-),10,FLEC-FAC attacked a patrol of the Angolan Arme...,4
5,Benin,Military Forces of Benin (2016-),JNIM: Group for Support of Islam and Muslims,13,Beninese military clashed with suspected JNIM ...,5
6,Brazil,Military Forces of Brazil (2023-) Military Police,Unidentified Gang (Brazil),6,"in Londrina (Parana), six drug trafficking sus...",6
7,Brazil,Unidentified Gang and/or Police Militia,Unidentified Gang (Brazil),6,"in Alto Garcas (Mato Grosso), unknown armed in...",7
8,Burkina Faso,Islamic State Sahel Province (ISSP),Civilians (Burkina Faso),75,IS Sahel militants attacked a Catholic church ...,8
9,Burkina Faso,Islamic State Sahel Province (ISSP),Military Forces of Burkina Faso (2022-),8,IS Sahel militants clashed with soldiers at ea...,9

## Creating sentence embeddings for grouped event notes:

In [92]:
model = SentenceTransformer('all-MiniLM-L6-v2')

def compute_and_cache_embeddings(df, text_column, model, cache_path, reset = False):
    """
    Computes and saves embeddings for a text column.
    """
    if reset == False:
        embeddings = np.load(cache_path)
        print("Loaded embeddings from cache.")
        return embeddings
        
    else:
        texts = df[text_column].fillna("").tolist()
        embeddings = model.encode(texts, batch_size=64, show_progress_bar=True, convert_to_numpy=True)
        np.save(cache_path, embeddings)
        return embeddings

In [93]:
grouped_event_embeddings = compute_and_cache_embeddings(acled_events_grouped, "notes", model, 
                                              f"data/mst/sentence_embeddings/02_events_grouped_embeddings.npy",
                                                       reset = False)

Loaded embeddings from cache.

## Cross joining news and events

In [94]:
# setting arbitrary cross join keys
acled_events_grouped['cross_join_key'] = 1
nyt_articles['cross_join_key'] = 1

In [95]:
# cross join
merged_grouped_events = pd.merge(acled_events_grouped, nyt_articles, on = 'cross_join_key').drop('cross_join_key', axis = 1)

In [96]:
merged_grouped_events.head()

<bound method NDFrame.head of              country                                  actor1  \
0        Afghanistan  Islamic State Khorasan Province (ISKP)
1        Afghanistan  Islamic State Khorasan Province (ISKP)
2        Afghanistan  Islamic State Khorasan Province (ISKP)
3        Afghanistan  Islamic State Khorasan Province (ISKP)
4        Afghanistan  Islamic State Khorasan Province (ISKP)
...              ...                                     ...
5483547        Yemen     Unidentified Tribal Militia (Yemen)
5483548        Yemen     Unidentified Tribal Militia (Yemen)
5483549        Yemen     Unidentified Tribal Militia (Yemen)
5483550        Yemen     Unidentified Tribal Militia (Yemen)
5483551        Yemen     Unidentified Tribal Militia (Yemen)

                                          actor2  fatalities  \
0         Military Forces of Afghanistan (2021-)          22
1         Military Forces of Afghanistan (2021-)          22
2         Military Forces of Afghanistan (2021-)          22
3         Military Forces of Afghanistan (2021-)          22
4         Military Forces of Afghanistan (2021-)          22
...                                          ...         ...
5483547  Military Forces of Yemen (2017-) Houthi          20
5483548  Military Forces of Yemen (2017-) Houthi          20
5483549  Military Forces of Yemen (2017-) Houthi          20
5483550  Military Forces of Yemen (2017-) Houthi          20
5483551  Military Forces of Yemen (2017-) Houthi          20

                                                     notes  event_index  \
0        21-43 Taliban members and civilians were kille...            0
1        21-43 Taliban members and civilians were kille...            0
2        21-43 Taliban members and civilians were kille...            0
3        21-43 Taliban members and civilians were kille...            0
4        21-43 Taliban members and civilians were kille...            0
...                                                    ...          ...
5483547  unidentified armed tribesmen ambushed Houthi f...          463
5483548  unidentified armed tribesmen ambushed Houthi f...          463
5483549  unidentified armed tribesmen ambushed Houthi f...          463
5483550  unidentified armed tribesmen ambushed Houthi f...          463
5483551  unidentified armed tribesmen ambushed Houthi f...          463

         Unnamed: 0                                          nyt_title  \
0                 0  PGA Tour and Saudi-Backed LIV Extend Deadline ...
1                 1                               Something to Whistle
2                 2  U.S. Helicopters Sink 3 Houthi Boats in Red Se...
3                 3  In Times Square, Hundreds of Thousands Ring In...
4                 4  Quotation of the Day: In a Jewish-Arab School,...
...             ...                                                ...
5483547       11813      Beyoncé’s Country Is America: Every Bit of It
5483548       11814                    How to Use Up Those Easter Eggs
5483549       11815        Deep-Sixing Pornographic Deepfakes for Good
5483550       11816  Esther Coopersmith, Washington Hostess and Dip...
5483551       11817  Lorraine Graves, Pioneering Harlem Ballerina, ...

           nyt_date                                       nyt_abstract  \
0        2024-01-01  The tentative deal for the men’s golf circuits...
1        2024-01-01        Harry Zheng makes his New York Times debut.
2        2024-01-01  Iranian-backed Houthi gunmen from Yemen had fi...
3        2024-01-01  New Year’s celebrations took place as proteste...
4        2024-01-01  Quotation of the Day for Monday, January 1, 2024.
...             ...                                                ...
5483547  2024-03-31  On the bold, sprawling “Cowboy Carter,” the su...
5483548  2024-03-31  Deviled eggs, for sure. Maybe pickled eggs, cu...
5483549  2024-03-31  Responses to a column by Nicholas Kristof. Als...
5483550  2024-03-31  A place at her dinner tables, which sat 75, pr...
5483551  2024-03-31  Tall and commanding, she dazzled audiences as ...

                                                   nyt_url  news_index  index
0        https://www.nytimes.com/2023/12/31/business/de...           0      0
1        https://www.nytimes.com/2023/12/31/crosswords/...           1      1
2        https://www.nytimes.com/2023/12/31/world/middl...           2      2
3        https://www.nytimes.com/2023/12/31/nyregion/ti...           3      3
4        https://www.nytimes.com/2023/12/31/pageoneplus...           4      4
...                                                    ...         ...    ...
5483547  https://www.nytimes.com/2024/03/31/arts/music/...       11813  11813
5483548  https://www.nytimes.com/2024/03/31/dining/how-...       11814  11814
5483549  https://www.nytimes.com/2024/03/31/opinion/por...       11815  11815
5483550  https://www.nytimes.com/2024/03/31/us/esther-c...       11816  11816
5483551  https://www.nytimes.com/2024/03/31/arts/music/...       11817  11817

[5483552 rows x 13 columns]>

## Computing cosine similarities

### Computing all pairwise cossims

In [97]:
cossim_news_events_grouped = cosine_similarity(nyt_embeddings, grouped_event_embeddings)

### Grabbing relevant cossim and binding with df

In [100]:
merged_grouped_with_similarities = merged_grouped_events.assign(cosine_sim = lambda x: cossim_news_events_grouped[x['news_index'], x['event_index']]).drop(columns = ['Unnamed: 0', "index"])

In [101]:
merged_grouped_with_similarities.head()

,country,actor1,actor2,fatalities,notes,event_index,nyt_title,nyt_date,nyt_abstract,nyt_url,news_index,cosine_sim
0,Afghanistan,Islamic State Khorasan Province (ISKP),Military Forces of Afghanistan (2021-),22,21-43 Taliban members and civilians were kille...,0,PGA Tour and Saudi-Backed LIV Extend Deadline ...,2024-01-01,The tentative deal for the men’s golf circuits...,https://www.nytimes.com/2023/12/31/business/de...,0,0.061731
1,Afghanistan,Islamic State Khorasan Province (ISKP),Military Forces of Afghanistan (2021-),22,21-43 Taliban members and civilians were kille...,0,Something to Whistle,2024-01-01,Harry Zheng makes his New York Times debut.,https://www.nytimes.com/2023/12/31/crosswords/...,1,0.010037
2,Afghanistan,Islamic State Khorasan Province (ISKP),Military Forces of Afghanistan (2021-),22,21-43 Taliban members and civilians were kille...,0,U.S. Helicopters Sink 3 Houthi Boats in Red Se...,2024-01-01,Iranian-backed Houthi gunmen from Yemen had fi...,https://www.nytimes.com/2023/12/31/world/middl...,2,0.363066
3,Afghanistan,Islamic State Khorasan Province (ISKP),Military Forces of Afghanistan (2021-),22,21-43 Taliban members and civilians were kille...,0,"In Times Square, Hundreds of Thousands Ring In...",2024-01-01,New Year’s celebrations took place as proteste...,https://www.nytimes.com/2023/12/31/nyregion/ti...,3,0.214212
4,Afghanistan,Islamic State Khorasan Province (ISKP),Military Forces of Afghanistan (2021-),22,21-43 Taliban members and civilians were kille...,0,"Quotation of the Day: In a Jewish-Arab School,...",2024-01-01,"Quotation of the Day for Monday, January 1, 2024.",https://www.nytimes.com/2023/12/31/pageoneplus...,4,0.006634

### Exporting

In [102]:
merged_grouped_with_similarities.to_csv(f"data/mst/02_grouped_event_news_similarity.csv")